### PR TITLE
[WIP] Reusing and annotating the IPT guides

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Comment by chrisns** [comment]
@nick-otter @david-wirelab @tomfitzherbert @cassidti:
Please review these docs ASAP, the build standards is probably the more interesting one. the annotations in the right hand columns are only to describe our test automation, but I expect us to be adopting all the standards there (except the ones I've written `won't`) next to.
If you disagree/have comments now is very much the time to make them before they get set in stone :)

**Review by nick-otter — COMMENTED** [review]
Read

**Review by cassidti — CHANGES_REQUESTED** [review]
All fine at this stage except - ESG04 Security Group Standards, looks too over the top. I'll defer though to David for more specific points/suggestions.

**Review by david-wirelab — COMMENTED** [review]
ESG04 - I'd use one SG for EC2 instances and from the three listed "Service security group" would be best to choose.

**Comment by chrisns** [comment]
ESG04 amended

**Comment by cassidti** [comment]
Can we close this one now?

**Pull request closed without merging**
